version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: victorzenezi2/node-example
    container_name: app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    environment: 
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: victorzenezi2/nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on: 
      - mysql
      - app